INSERT INTO bears ("Mr. Chocolate", 1, M, black, nice, Y)
INSERT INTO bears ("Rowdy", 1, M, black, nice, Y)
INSERT INTO bears ("Tabitha", 1, M, black, nice, Y)
INSERT INTO bears ("Segeant Brown", 1, M, black, nice, Y)
INSERT INTO bears ("Melissa", 1, M, black, nice, Y)
INSERT INTO bears ("Grinch", 1, M, black, nice, Y)
INSERT INTO bears ("Wendy", 1, M, black, nice, Y)
INSERT INTO bears ("", 1, M, black, nice, Y)
